title: Precession
TR: 10
B0: 1.5
components:
  - name: ''
    CS: 1.5658
locations:
  [[1, 1, 1, 1, 1, 1, 1],
   [1, 1, 1, 1, 1, 1, 1],
   [1, 1, 1, 1, 1, 1, 1],
   [1, 1, 1, 1, 1, 1, 1],
   [1, 1, 1, 1, 1, 1, 1],
   [1, 1, 1, 1, 1, 1, 1],
   [1, 1, 1, 1, 1, 1, 1]]
M0:
  [[[1, 0, 15], [1, 0, 15], [1, 0, 15], [1, 0, 15], [1, 0, 15], [1, 0, 15], [1, 0, 15]], 
   [[1, 0, 15], [1, 0, 15], [1, 0, 15], [1, 0, 15], [1, 0, 15], [1, 0, 15], [1, 0, 15]],
   [[1, 0, 15], [1, 0, 15], [1, 0, 15], [1, 0, 15], [1, 0, 15], [1, 0, 15], [1, 0, 15]],
   [[1, 0, 15], [1, 0, 15], [1, 0, 15], [1, 0, 15], [1, 0, 15], [1, 0, 15], [1, 0, 15]],
   [[1, 0, 15], [1, 0, 15], [1, 0, 15], [1, 0, 15], [1, 0, 15], [1, 0, 15], [1, 0, 15]],
   [[1, 0, 15], [1, 0, 15], [1, 0, 15], [1, 0, 15], [1, 0, 15], [1, 0, 15], [1, 0, 15]],
   [[1, 0, 15], [1, 0, 15], [1, 0, 15], [1, 0, 15], [1, 0, 15], [1, 0, 15], [1, 0, 15]]]
speed: 0.01
output:
  - type: 3D
    file: precession.gif