title: Random precession and relaxation
TR: 150
B0: 1.5
components:
  - name: ''
    CS: 1.5658
    T1: 30
    T2: 30
locations:
  [[.75, .75, .75, .75, .75, .75, .75],
   [.75, .75, .75, .75, .75, .75, .75],
   [.75, .75, .75, .75, .75, .75, .75],
   [.75, .75, .75, .75, .75, .75, .75],
   [.75, .75, .75, .75, .75, .75, .75],
   [.75, .75, .75, .75, .75, .75, .75],
   [.75, .75, .75, .75, .75, .75, .75]]
M0:
  [[[1,115,33], [1,227,37], [1,18,102], [1,4,159], [1,67,91], [1,301,53], [1,141,60]], 
   [[1,170,148], [1,9,148], [1,300,9], [1,91,136], [1,244,133], [1,251,49], [1,198,53]], 
   [[1,78,38], [1,71,26], [1,165,18], [1,57,75], [1,259,128], [1,114,100], [1,317,126]], 
   [[1,276,76], [1,164,137], [1,55,14], [1,166,18], [1,245,31], [1,175,15], [1,10,81]], 
   [[1,29,133], [1,190,128], [1,98,97], [1,323,24], [1,180,56], [1,156,91], [1,301,14]], 
   [[1,14,103], [1,213,12], [1,297,155], [1,171,154], [1,86,11], [1,309,27], [1,137,47]], 
   [[1,173,67], [1,61,22], [1,261,105], [1,311,38], [1,247,124], [1,32,132], [1,132,176]]]
speed: 0.01
output:
  - type: 3D
    file: randomPrecessionRelaxation.gif