title: TOF
TR: 10
nTR: 1
nDummies: 10
B0: 1.5
pulseSeq:
  - t: 0
    FA: 30
    dur: 3
    Gz: 30
  - t: 10
    spoil: true
components:
  - name: still
    T1: 1000
    T2: 100
  - name: flow
    T1: 1000
    T2: 100
    vz: -100
locations:
  'still':
    [[[.00, .00, .00, .00, .00, .00, .00],
      [.00, .00, .00, .00, .00, .00, .00],
      [.00, .00, .00, .00, .00, .00, .00],
      [.00, .00, .00, .00, .00, .00, .00],
      [.00, .00, .00, .00, .00, .00, .00],
      [.00, .00, .00, .00, .00, .00, .00],
      [.00, .00, .00, .00, .00, .00, .00]],
     [[.00, .00, .00, .00, .00, .00, .00],
      [.00, .00, .00, .00, .00, .00, .00],
      [.00, .00, .00, .00, .00, .00, .00],
      [.00, .00, .00, .00, .00, .00, .00],
      [.00, .00, .00, .00, .00, .00, .00],
      [.00, .00, .00, .00, .00, .00, .00],
      [.00, .00, .00, .00, .00, .00, .00]],
     [[.00, .00, .75, .75, .75, .75, .00],
      [.75, .75, .75, .75, .75, .75, .75],
      [.75, .75, .75, .75, .75, .75, .75],
      [.75, .75, .75, .00, .75, .75, .75],
      [.75, .75, .75, .75, .75, .75, .75],
      [.75, .75, .75, .75, .75, .75, .75],
      [.00, .75, .75, .75, .75, .00, .00]],     
     [[.00, .00, .00, .00, .00, .00, .00],
      [.00, .00, .00, .00, .00, .00, .00],
      [.00, .00, .00, .00, .00, .00, .00],
      [.00, .00, .00, .00, .00, .00, .00],
      [.00, .00, .00, .00, .00, .00, .00],
      [.00, .00, .00, .00, .00, .00, .00],
      [.00, .00, .00, .00, .00, .00, .00]],     
     [[.00, .00, .00, .00, .00, .00, .00],
      [.00, .00, .00, .00, .00, .00, .00],
      [.00, .00, .00, .00, .00, .00, .00],
      [.00, .00, .00, .00, .00, .00, .00],
      [.00, .00, .00, .00, .00, .00, .00],
      [.00, .00, .00, .00, .00, .00, .00],
      [.00, .00, .00, .00, .00, .00, .00]]]
  'flow':
    [[[.00, .00, .00, .00, .00, .00, .00],
      [.00, .00, .00, .00, .00, .00, .00],
      [.00, .00, .00, .00, .00, .00, .00],
      [.00, .00, .00, .00, .00, .00, .00],
      [.00, .00, .00, .00, .00, .00, .00],
      [.00, .00, .00, .00, .00, .00, .00],
      [.00, .00, .00, .00, .00, .00, .00]],
     [[.00, .00, .00, .00, .00, .00, .00],
      [.00, .00, .00, .00, .00, .00, .00],
      [.00, .00, .00, .00, .00, .00, .00],
      [.00, .00, .00, .00, .00, .00, .00],
      [.00, .00, .00, .00, .00, .00, .00],
      [.00, .00, .00, .00, .00, .00, .00],
      [.00, .00, .00, .00, .00, .00, .00]],
     [[.00, .00, .00, .00, .00, .00, .00],
      [.00, .00, .00, .00, .00, .00, .00],
      [.00, .00, .00, .00, .00, .00, .00],
      [.00, .00, .00, .75, .00, .00, .00],
      [.00, .00, .00, .00, .00, .00, .00],
      [.00, .00, .00, .00, .00, .00, .00],
      [.00, .00, .00, .00, .00, .00, .00]],
     [[.00, .00, .00, .00, .00, .00, .00],
      [.00, .00, .00, .00, .00, .00, .00],
      [.00, .00, .00, .00, .00, .00, .00],
      [.00, .00, .00, .75, .00, .00, .00],
      [.00, .00, .00, .00, .00, .00, .00],
      [.00, .00, .00, .00, .00, .00, .00],
      [.00, .00, .00, .00, .00, .00, .00]],
     [[.00, .00, .00, .00, .00, .00, .00],
      [.00, .00, .00, .00, .00, .00, .00],
      [.00, .00, .00, .00, .00, .00, .00],
      [.00, .00, .00, .75, .00, .00, .00],
      [.00, .00, .00, .00, .00, .00, .00],
      [.00, .00, .00, .00, .00, .00, .00],
      [.00, .00, .00, .00, .00, .00, .00]]]
speed: .005
maxRFspeed: .005
output:
  - type: 3D
    file: TOF_3D.gif